In [16]:
import cupy as cp
import scipy
from scipy import integrate

计算：
$$
\pi = I(f) =\int_{0}^{1}\frac{4}{1+x^2}dx
$$


In [17]:
def f(x):
    return 4/(1+cp.power(x, 2))

In [22]:
%%time
# 积分：
integrate.quad(f, 0, 1)

Wall time: 8 ms


(3.141592653589794, 3.4878684980086326e-14)

In [19]:
def integ1d(f, x1, xn, n):
    x = cp.linspace(x1, xn, n)
    stepx = (xn - x1)/n
    return cp.sum(f(x)) * stepx

In [20]:
def g(x):
    return 4/(1+cp.power(x, 2))

def fg(x):
    return f(x) * g(x)

In [24]:
integrate.quad(fg, 0, 1)

(10.283185307179588, 1.1416629094517891e-13)

In [25]:
def integ1D(f,g, x1, xn, n):
    x = cp.linspace(x1, xn, n)
    stepx = (xn - x1)/n
    return cp.dot(f(x), g(x)) * stepx

In [34]:
integ1D(f, g, 0, 1, 100000)

array(10.28318248)

# 二维积分
下面例子的函数见：  
https://www.cnblogs.com/Yanjy-OnlyOne/p/11185582.html  
$$I(f(x, y))=\int_{1}^{2} \int_{1}^{x} x y d x d y$$

In [106]:
def f(x, y):
    return x * y
def h(x):
    return x

v, err = integrate.dblquad(f, 1, 2, lambda x: 1, 2) # 简化函数，矩形积分边界，而不是上面例子中的三角形边界

In [107]:
v

2.2499999999999996

In [116]:
cp.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])

In [127]:
a = np.array([[1,2]])
b = np.array([[3,4]])

In [130]:
np.cross(np.array(a), np.array(b))

array([-2])

In [125]:
res = np.kron(a, b)

In [126]:
np.linalg.det(res)

16.000000000000078

In [120]:
cp.cross(a, b)

AttributeError: module 'cupy' has no attribute 'cross'

In [104]:
from pprint import pprint
def integ2d(f,g, x1, xn, y1, yn, n):
    x = cp.linspace(x1, xn, n)[None,...]
    y = cp.linspace(y1, yn, n)[...,None]
    stepx = (xn - x1)/n
    stepy = (yn - y1)/n
    res = cp.kron(x, y)
    pprint(res, width=200, depth=2)
    return cp.linalg.det(res)

In [105]:
integ2d(f, g, 1, 2, 1, 2, 100)

array([[1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ],
       [1.11111111, 1.2345679 , 1.35802469, 1.48148148, 1.60493827,
        1.72839506, 1.85185185, 1.97530864, 2.09876543, 2.22222222],
       [1.22222222, 1.35802469, 1.49382716, 1.62962963, 1.7654321 ,
        1.90123457, 2.03703704, 2.17283951, 2.30864198, 2.44444444],
       [1.33333333, 1.48148148, 1.62962963, 1.77777778, 1.92592593,
        2.07407407, 2.22222222, 2.37037037, 2.51851852, 2.66666667],
       [1.44444444, 1.60493827, 1.7654321 , 1.92592593, 2.08641975,
        2.24691358, 2.40740741, 2.56790123, 2.72839506, 2.88888889],
       [1.55555556, 1.72839506, 1.90123457, 2.07407407, 2.24691358,
        2.41975309, 2.59259259, 2.7654321 , 2.9382716 , 3.11111111],
       [1.66666667, 1.85185185, 2.03703704, 2.22222222, 2.40740741,
        2.59259259, 2.77777778, 2.96296296, 3.14814815, 3.33333333],
       [1.77777778, 1.97530864, 2.1728395

array(0.)

In [100]:
np.linalg.det(np.array([[1, 2], [3, 4]]))

-2.0000000000000004

In [101]:
cp.linalg.det(cp.array([[1, 2], [3, 4]]))

array(-2.)

In [47]:
a = np.ones((5,5))

In [48]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.linalg.det(a)

0.0